[project]
name = "nim"
version = "0.1.0"
description = "Add your description here"
readme = "README.rst"
authors = [
    { name = "Charles Bouchard-Légaré", email = "charlesbouchardlegare@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "click>=8.5.0",
]

[project.scripts]
nim = "nim.run:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "coverage>=7.16.2",
    "mypy>=2.4.0",
    "nox[uv]>=2026.8.17",
    "pytest>=9.1.1",
]
